import asyncio

from backend.services.iac_analysis_service import IacAnalysisService


TERRAFORM_SAMPLE = """
resource \"aws_instance\" \"demo\" {
  ami           = \"ami-123\"
  instance_type = \"m5.large\"
}

resource \"aws_db_instance\" \"db\" {
  identifier  = \"demo-dev-db\"
  multi_az    = true
}

resource \"aws_ebs_volume\" \"data\" {
  volume_type = \"gp2\"
}
"""


CLOUDFORMATION_SAMPLE = """
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  App:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: m5.xlarge
  Db:
    Type: AWS::RDS::DBInstance
    Properties:
      MultiAZ: true
"""


def test_analyze_terraform_generates_signals():
    svc = IacAnalysisService()

    record = asyncio.run(
        svc.analyze_file(
            filename="demo.tf",
            content=TERRAFORM_SAMPLE,
            owner_user_id="u1",
            owner_org_id="o1",
        )
    )

    assert record.format == "terraform"
    assert record.analysis_id
    assert any("gp2" in c.lower() for c in record.cons)
    assert any(row["estimated_monthly_cost_usd"] > 0 for row in record.cost_analysis)
    assert "Generated by FinOps Orchestrator" in record.improved_content


def test_analyze_cloudformation_detects_multi_az():
    svc = IacAnalysisService()

    record = asyncio.run(
        svc.analyze_file(
            filename="stack.yaml",
            content=CLOUDFORMATION_SAMPLE,
            owner_user_id="u1",
            owner_org_id="o1",
        )
    )

    assert record.format == "cloudformation"
    assert any("multiaz" in c.lower().replace("-", "") or "multiaz" in c.lower().replace(" ", "") for c in record.cons)


def test_generate_final_version_updates_content():
    svc = IacAnalysisService()

    record = asyncio.run(
        svc.analyze_file(
            filename="demo.tf",
            content=TERRAFORM_SAMPLE,
            owner_user_id="u1",
            owner_org_id="o1",
        )
    )

    updated = asyncio.run(
        svc.generate_final_version(
            analysis_id=record.analysis_id,
            goals="Prioritize lowest cost for development environments",
            user_id="u1",
            org_id="o1",
        )
    )

    assert updated.improved_content
    assert len(updated.improved_content) > 30


def test_owner_check_blocks_other_user():
    svc = IacAnalysisService()

    record = asyncio.run(
        svc.analyze_file(
            filename="demo.tf",
            content=TERRAFORM_SAMPLE,
            owner_user_id="owner-user",
            owner_org_id="org-1",
        )
    )

    try:
        asyncio.run(
            svc.chat_about_template(
                analysis_id=record.analysis_id,
                question="Can I remove Multi-AZ?",
                user_id="different-user",
                org_id="org-1",
            )
        )
        assert False, "Expected PermissionError"
    except PermissionError:
        assert True


def test_analyze_files_returns_cross_file_payload():
    svc = IacAnalysisService()
    files = [
        ("network.tf", 'resource "aws_instance" "web" {\n  instance_type = "m5.xlarge"\n}\n'),
        ("compute.tf", 'resource "aws_instance" "web" {\n  instance_type = "m5.large"\n}\n'),
    ]

    result = asyncio.run(svc.analyze_files(files=files, owner_user_id="u2", owner_org_id="o1"))

    assert result["file_count"] == 2
    assert len(result["records"]) == 2
    assert result["primary"].filename == "network.tf"
    assert isinstance(result["cross_file_analysis"]["architecture_observations"], list)
    assert isinstance(result["cross_file_analysis"]["recommendations"], list)
    assert result["cross_file_analysis"]["total_estimated_monthly_savings"] >= 0


def test_cross_file_analysis_detects_duplicates_and_regions():
    svc = IacAnalysisService()
    files = [
        ("main.tf", 'provider "aws" { region = "us-east-1" }\nresource "aws_instance" "api" {\n  instance_type = "m5.xlarge"\n}\n'),
        ("secondary.tf", 'provider "aws" { region = "us-west-2" }\nresource "aws_instance" "api" {\n  instance_type = "m5.large"\n}\n'),
    ]

    result = asyncio.run(svc.analyze_files(files=files, owner_user_id="u3", owner_org_id="o1"))
    cross = result["cross_file_analysis"]

    duplicate_details = "\n".join(cross.get("duplicate_resource_details", []))
    assert "aws_instance.api" in duplicate_details
    assert set(cross.get("regions_detected", [])) == {"us-east-1", "us-west-2"}
